name: Generate and Deploy Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'Graph Analysis/unified_analysis.py'
      - '.github/workflows/pages.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate HTML report
      run: |
        python "Graph Analysis/unified_analysis.py" --html --html-output docs/index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

